name: learnyounode tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      # This step checks out a copy of your repository.
      - name: Check out repository to run tests against
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm start
        env:
          CI: true
